### ISSUE TITLE
gazebo GUI doesn't show up

### ISSUE THREAD

**Issue by RIckyBan** [AcutronicRobotics/gym-gazebo2#38]
Hi gym-gazebo2 developers, thank you for your wonderful product. I have a problem as below.

**Version**
Ubuntu: 18.04.2 LTS (Bionic Beaver)
gazebo: 9.0.0
python: 3.6.7
ROS: crystal

**Bug & Error trace**
After completely following INSTALL.md, when I run

```
~/gym-gazebo2/examples/MARA$ python3 gg_random.py -g
```
it fails and gazebo GUI doesn't show up like this.

<details>
 <summary>Click to expand</summary>

```
~/gym-gazebo2/examples/MARA$ python3 gg_random.py -g
[INFO] [launch]: process[gazebo-1]: started with pid [19349]
[INFO] [launch]: process[spawn_mara.py-2]: started with pid [19350]
[INFO] [launch]: process[hros_cognition_mara_components-3]: started with pid [19351]
[INFO] [launch]: process[mara_contact_publisher-4]: started with pid [19352]
[INFO] [launch]: process[spawn_mara.py-2]: process has finished cleanly
[ERROR] [launch]: process[mara_contact_publisher-4] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [launch]: sending signal 'SIGTERM' to process[mara_contact_publisher-4]
[ERROR] [launch]: process[mara_contact_publisher-4] process has died [pid 19170, exit code -15, cmd '/home/USERNAME/ros2_mara_ws/install/lib/mara_contact_publisher/mara_contact_publisher'].
[ERROR] [launch]: process[gazebo-1] process has died [pid 19349, exit code 255, cmd 'gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/USERNAME/gym-gazebo2/gym_gazebo2/worlds/empty__state_plugin__speed_up.world'].
^CTraceback (most recent call last):
  File "gg_random.py", line 16, in <module>
[WARNING] [launch.LaunchService]: user interrupted with ctrl-c (SIGINT)
    observation, reward, done, info = env.step(env.action_space.sample())
  File "/home/USERNAME/gym-gazebo2/gym_gazebo2/envs/MARA/mara.py", line 308, in step
    obs = self.take_observation()
  File "/home/USERNAME/gym-gazebo2/gym_gazebo2/envs/MARA/mara.py", line 235, in take_observation
    rclpy.spin_once(self.node)
  File "/opt/ros/crystal/lib/python3.6/site-packages/rclpy/__init__.py", line 98, in spin_once
    executor.spin_once(timeout_sec=timeout_sec)
  File "/opt/ros/crystal/lib/python3.6/site-packages/rclpy/executors.py", line 566, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/crystal/lib/python3.6/site-packages/rclpy/executors.py", line 549, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/crystal/lib/python3.6/site-packages/rclpy/executors.py", line 445, in _wait_for_ready_callbacks
    _rclpy.rclpy_wait(wait_set, timeout_nsec)
  File "/opt/ros/crystal/lib/python3.6/site-packages/launch/utilities/signal_management.py", line 120, in __on_sigint
    __original_sigint_handler(signum, frame)
KeyboardInterrupt
[INFO] [launch]: process[hros_cognition_mara_components-3]: process has finished cleanly

```
</details>

In turn running the specific died process,

```
~/gym-gazebo2/examples/MARA$ gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/USERNAME/gym-gazebo2/gym_gazebo2/worlds/empty__state_plugin__speed_up.world
```

it turns out that the gazebo cannot find config file.

<details>
 <summary>Click to expand</summary>

```
~/gym-gazebo2/examples/MARA$ gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/USERNAME/gym-gazebo2/gym_gazebo2/worlds/empty__state_plugin__speed_up.world
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.16.0.119
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/physics/contacts, deleting message. This warning is printed only once.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.16.0.119
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/ament_index"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/colcon-core"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/doc"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/gripper_minimal_service"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/gripper_minimal_subscriber"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hans_modular_gazebo"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hans_t30_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hans_t49_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hans_t9_4_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hrim_actuator_gripper_msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hrim_actuator_gripper_srvs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hrim_actuator_rotaryservo_actions"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hrim_actuator_rotaryservo_msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hrim_actuator_rotaryservo_srvs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hrim_generic_msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hrim_generic_srvs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/hros_cognition_mara_components"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_bringup"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_contact_publisher"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_gazebo"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_gazebo_plugins"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_minimal_publisher"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_minimal_subscriber"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_minimal_trajectory_action"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/mara_utils_scripts"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/orocos_kdl"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/python_orocos_kdl"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/robotiq_140_gripper_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/robotiq_85_gripper_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/robotiq_gazebo"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/robotiq_gripper_gazebo_plugins"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/robotiq_hande_gripper_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/USERNAME/ros2_mara_ws/install/share/urdfdom_py"
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
```
</details>

As in `ros2_mara_ws/install/share` I can't find no config file in each directory so it's natural but I don't understand how I made a mistake. Is there any way to avoid this?

Thank you.

**Comment by alesolano** [comment]
Hi @RIckyBan, thanks for reporting! You need gazebo 9.9.0. Please refer to [this](https://github.com/AcutronicRobotics/gym-gazebo2/issues/27#issuecomment-504311404) for the upgrade.

**Comment by RIckyBan** [comment]
Hi @alesolano, thank you for quick response! I'm sorry I haven't read closed issues, I'll try and report it to you.

**Comment by RIckyBan** [comment]
After upgrade to gazebo 9.9.0, it worked fine! Thank you very much.

![Screenshot from 2019-07-01 15-21-17](https://user-images.githubusercontent.com/27843263/60423842-03ee0200-9c2a-11e9-824d-4ebd679473f2.png)
